from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from src.models.base import Base, TenantOwnedMixin


class EditorialPackage(Base, TenantOwnedMixin):
    """Editorial output generated by the pipeline for a project.

    One package per project. Contains all AI-generated text assets
    ready for journalist review before publication.
    """

    __tablename__ = "editorial_packages"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    project_id: Mapped[UUID] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,   # one package per project
        index=True,
    )
    web_article: Mapped[str | None] = mapped_column(Text)           # ~300 words, markdown
    tweet: Mapped[str | None] = mapped_column(Text)                 # max 280 chars
    executive_summary: Mapped[str | None] = mapped_column(Text)     # 2-3 sentences
    angle_proposals: Mapped[list | None] = mapped_column(JSONB)     # list of str
    voiceover_script: Mapped[str | None] = mapped_column(Text)      # voz en off completa
    voiceover_audio_key: Mapped[str | None] = mapped_column(Text)   # storage key
    composed_video_key: Mapped[str | None] = mapped_column(Text)    # storage key of final MP4
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
