"""add tv_pieces column to editorial_packages

Revision ID: 015cd699c453
Revises: 0002
Create Date: 2026-05-11 21:36:37.094660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '015cd699c453'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editorial_packages', sa.Column('tv_pieces', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editorial_packages', 'tv_pieces')
    # ### end Alembic commands ###
